## Instance-based learning w/ k-Nearest Neighbor

In [1]:
import numpy as np
import pandas as pd
import scipy

import matplotlib.pyplot as plt
from pylab import rcParams
import seaborn as sns

import urllib

In [2]:
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors, preprocessing

from sklearn.model_selection import train_test_split
from sklearn import metrics

In [3]:
#Now let's set our plotting parameters for the Jupyter notebook.
np.set_printoptions(precision=4, suppress=True) 
%matplotlib inline
rcParams['figure.figsize'] = 7, 4
sns.set_style("whitegrid")

In [ ]:
# Descrição das colunas do dataset 'cars' (mtcars)
# car_names : Nome do carro.
#             Ex.: Mazda RX4
# mpg       : Consumo de combustível em milhas por galão (Miles Per Gallon).
#             Ex.: 21.0
# cyl       : Número de cilindros do motor.
#             Ex.: 4, 6 ou 8
# disp      : Cilindrada (deslocamento do motor), em polegadas cúbicas (Cubic Inches).
#             Ex.: 160.0
# hp        : Potência do motor, em cavalos-vapor (Horsepower).
#             Ex.: 110
# drat      : Relação do eixo traseiro (Rear Axle Ratio).
#             Ex.: 3.90
# wt        : Peso do veículo, em milhares de libras.
#             Ex.: 2.620 = 2620 lb
# qsec      : Tempo para percorrer 1/4 de milha, em segundos.
#             Ex.: 16.46
# vs        : Tipo do motor.
#             0 = Motor em V
#             1 = Motor em linha (Straight)
# am        : Tipo de transmissão.
#             0 = Automática
#             1 = Manual
# gear      : Número de marchas da transmissão.
#             Ex.: 3, 4 ou 5
# carb      : Número de carburadores.
#             Ex.: 1, 2, 3, 4, 6 ou 8

address = 'G:\\Meu Drive\\Cursos\\Python\\MachineLearning\\Parte2\\data\\mtcars.csv'

cars = pd.read_csv(address)
cars.columns = ['car_names','mpg','cyl','disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
cars


,car_names,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4


In [ ]:
#.values converte essa coluna em um array do NumPy.
# mpg       : Consumo de combustível em milhas por galão (Miles Per Gallon).
#             Ex.: 21.0
# disp      : Cilindrada (deslocamento do motor), em polegadas cúbicas (Cubic Inches).
#             Ex.: 160.0
# hp        : Potência do motor, em cavalos-vapor (Horsepower).
#             Ex.: 110
# wt        : Peso do veículo, em milhares de libras.
#             Ex.: 2.620 = 2620 lb

x_prime = cars[['mpg','disp','hp','wt',]].values
x_prime


array([[ 21.   , 160.   , 110.   ,   2.62 ],
       [ 21.   , 160.   , 110.   ,   2.875],
       [ 22.8  , 108.   ,  93.   ,   2.32 ],
       [ 21.4  , 258.   , 110.   ,   3.215],
       [ 18.7  , 360.   , 175.   ,   3.44 ],
       [ 18.1  , 225.   , 105.   ,   3.46 ],
       [ 14.3  , 360.   , 245.   ,   3.57 ],
       [ 24.4  , 146.7  ,  62.   ,   3.19 ],
       [ 22.8  , 140.8  ,  95.   ,   3.15 ],
       [ 19.2  , 167.6  , 123.   ,   3.44 ],
       [ 17.8  , 167.6  , 123.   ,   3.44 ],
       [ 16.4  , 275.8  , 180.   ,   4.07 ],
       [ 17.3  , 275.8  , 180.   ,   3.73 ],
       [ 15.2  , 275.8  , 180.   ,   3.78 ],
       [ 10.4  , 472.   , 205.   ,   5.25 ],
       [ 10.4  , 460.   , 215.   ,   5.424],
       [ 14.7  , 440.   , 230.   ,   5.345],
       [ 32.4  ,  78.7  ,  66.   ,   2.2  ],
       [ 30.4  ,  75.7  ,  52.   ,   1.615],
       [ 33.9  ,  71.1  ,  65.   ,   1.835],
       [ 21.5  , 120.1  ,  97.   ,   2.465],
       [ 15.5  , 318.   , 150.   ,   3.52 ],
       [ 1

In [ ]:
# y = cars.iloc[:, 9].values
# Explicação:
# .values Pega apenas os dados como array e não o dataset
# faz três coisas:
# cars é um objeto do tipo DataFrame da biblioteca pandas.
# .iloc[:, 9] seleciona dados usando índices numéricos:
# : significa todas as linhas.
# 9 significa a décima coluna (a contagem começa em 0). Coluna "am" (Tipo de transmissão.)
# Ou seja, isso equivale a:
# cars.iloc[:, 9]
# = "pegue todas as linhas da coluna de índice 9 "am" (Tipo de transmissão.)".
y = cars.iloc[:,9].values
y

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# A função scale() da biblioteca sklearn.preprocessing padroniza os dados,
# transformando cada coluna para que tenha:

# - Média = 0
# - Desvio padrão = 1

# A transformação aplicada a cada valor é:

#     x_padronizado = (x - μ) / σ

# onde:
#     x = valor original;
#     μ = média da coluna;
#     σ = desvio padrão da coluna.

# A padronização coloca todas as variáveis na mesma escala, evitando que
# atributos com valores maiores tenham influência desproporcional no modelo.
# Exemplo de variáveis com escalas diferentes:

# Variável        Faixa de valores
# --------------------------------
# hp (potência)  : 50 a 350
# wt (peso)      : 1.5 a 5.5
# gear (marchas) : 3 a 5
# A padronização evita que variáveis com escalas muito diferentes dominem o treinamento de um modelo.
# Sem padronização, a variável hp pode ter muito mais influência simplesmente porque seus números são maiores. 
# Após scale(), todas as variáveis ficam na mesma escala, permitindo que o algoritmo trate cada uma de forma 
# mais equilibrada.

x = preprocessing.scale(x_prime)
x

array([[ 0.1533, -0.5798, -0.5437, -0.6202],
       [ 0.1533, -0.5798, -0.5437, -0.3554],
       [ 0.4567, -1.006 , -0.7956, -0.9317],
       [ 0.2207,  0.2236, -0.5437, -0.0023],
       [-0.2344,  1.0598,  0.4195,  0.2313],
       [-0.3356, -0.0469, -0.6177,  0.2521],
       [-0.9762,  1.0598,  1.4568,  0.3663],
       [ 0.7265, -0.6888, -1.2549, -0.0283],
       [ 0.4567, -0.7371, -0.7659, -0.0698],
       [-0.1501, -0.5174, -0.351 ,  0.2313],
       [-0.3861, -0.5174, -0.351 ,  0.2313],
       [-0.6222,  0.3695,  0.4936,  0.8855],
       [-0.4704,  0.3695,  0.4936,  0.5324],
       [-0.8244,  0.3695,  0.4936,  0.5843],
       [-1.6336,  1.9779,  0.8641,  2.1107],
       [-1.6336,  1.8795,  1.0123,  2.2914],
       [-0.9087,  1.7156,  1.2346,  2.2094],
       [ 2.0751, -1.2462, -1.1957, -1.0563],
       [ 1.7379, -1.2708, -1.4031, -1.6637],
       [ 2.3279, -1.3085, -1.2105, -1.4353],
       [ 0.2376, -0.9068, -0.7363, -0.7811],
       [-0.7739,  0.7155,  0.0491,  0.3144],
       [-0

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=17)

In [19]:
# Cria objeto KNeighborsClassifier
clf = neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",None
Name,Type,Value
"classes_ classes_: array of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"effective_metric_ effective_metric_: str or callbleThe distance metric used. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'


In [21]:
# y predito
y_pred = clf.predict(x_test)
# y esperado é o y de teste
y_expect = y_test

# cria metrica do modelo. Avaliando o y esperado com o y previsto
print(metrics.classification_report(y_expect,y_pred))


              precision    recall  f1-score   support

           0       0.80      1.00      0.89         4
           1       1.00      0.67      0.80         3

    accuracy                           0.86         7
   macro avg       0.90      0.83      0.84         7
weighted avg       0.89      0.86      0.85         7

